### ISSUE TITLE
Windows keyboard shortcut Ctrl+K already mapped

### ISSUE THREAD

**Issue by gavinjolly** [ndethore/swoop#11]
Sadly have not been able to use yet. I will try on my MAC tonight.

`Ctrl+K` is already mapped to a search ([Chrome keyboard shortcuts](https://support.google.com/chrome/answer/157179?hl=en)) and I cannot see how you can remap shortcut keys in Chrome.

**Comment by ndethore** [comment]
Great catch! I haven't got a chance to test the extension on windows.

You can remap Swoop!'s default shortcut by visiting chrome://extensions and clicking on "hamburger" menu on the top left corner of the screen. You should see a "Keyboard Shortcuts" section...

Not easy to find, I agree 😅 

Any suggestions for a replacement shortcut on Windows?

**Comment by gavinjolly** [comment]
I have chosen Ctrl+M for now. On the bottom row and Many is okay for me but that may not suit others.

BTW we, in the windows world do not have the hamburget menu. Instead we have a `Keyboard Shortcuts` 

![capture](https://user-images.githubusercontent.com/32151416/39271397-0df7e7f8-492d-11e8-8aba-c109b519d1cb.PNG)

**Comment by ndethore** [comment]
Going with Ctrl+M on windows. We can change it later, if needed.

Thanks a lot @gavinjolly 👽
