### ISSUE TITLE
Command + K is used for adding a link on most sites in Chrome on Mac

### ISSUE THREAD

**Issue by 3raxton** [ndethore/swoop#15]
The shortcut for Chrome on Mac is usually set as Command + K which is also the shortcut for Swoop! . Would you reconsider the shortcut for Swoop! on Mac?

**Comment by joshbuchea** [comment]
@3raxton in Chrome on Mac, Command + K typically a shortcut for "adding a link"..? Did you mean for adding a bookmark? If so, isn't the keyboard shortcut for that Command + D?

**Comment by 3raxton** [comment]
Woah! My apologies about the first part of this thread. What I meant to say was that the shortcut for adding a link. In my opinion, it would be ideal to change the shortcut from Command + K to something else as this is the regular shortcut for adding a hyperlink on a Mac. 

Please let me know if there is any confusion with this reply!

**Comment by joshbuchea** [comment]
My apologies @3raxton, I should have been more direct. In Chrome on macOS, the default keyboard shortcut for **adding a bookmark** is **Command + K**. What does **adding a hyperlink** mean? Also, **Command + K** doesn't seem to be a default keyboard shortcut for anything that I can find. Do you understand my confusion?

**Comment by joshbuchea** [comment]
Re-reading this thread, I feel come across a bit rude. I believe my original intent was only to clarify, but I'd like to apologize regardless for not employing more empathy in my responses 🙇
